### ISSUE TITLE
Doesn't work with new flutter 

### ISSUE THREAD

**Issue by caseyryan** [clovisnicolas/flutter_screen#16]
I'm trying to use the plugin with flutter 1.7 but I'm always getting this error

> E/flutter (22188): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method keepOn on channel github.com/clovisnicolas/flutter_screen)
> E/flutter (22188): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
> E/flutter (22188): <asynchronous suspension>
> E/flutter (22188): #1      Screen.keepOn (package:screen/screen.dart:11:45)

Seems like some dependencies are missing. I tried rebuilding the app completely. It didn't help

**Comment by caseyryan** [comment]
The problem can be resolved by right clicking android -> Refactor -> Migrate to AndroidX and a complete rebuild of the app
